name: Build and Test common libraries
on: push
jobs:
  setup_and_build_check:
    runs-on: ubuntu-22.04
    steps:
     - uses: actions/checkout@v4
     - name: build + test
       run: |
        cd common_libraries/
        make test
        